runtime: python37
#api_version: 1
#threadsafe: true
#handlers:
#- url: /static
#  static_dir: static
#- url: /.*
#  script: main.app

#libraries:
#  - name: ssl
#    version: latest

env_variables:
  CLOUD_SQL_USERNAME: pokemon_db_user
  CLOUD_SQL_PASSWORD: GottaCatch'EmAll!
  CLOUD_SQL_DATABASE_NAME: pokemon_database
  CLOUD_SQL_CONNECTION_NAME: best-pokemon:us-east4:best-pokemon-mysql-db
